In [3]:
import pandas as pd
import os

# 1. ระบุตำแหน่งไฟล์ (เปลี่ยนชื่อไฟล์ให้ตรงกับของคุณนะ)
file_path ="D:\\NaCl-Analysis-21X4\\Data\\data_Chem02_21X4.xlsx"

# 2. โหลดข้อมูล
df = pd.read_excel(file_path)

# 3. ดู 5 แถวแรกเพื่อเช็คหัวตาราง
print("--- 5 แถวแรกของข้อมูล ---")
display(df.head())

# 4. เช็คความพร้อมของข้อมูล (มี Missing value ไหม? ประเภทข้อมูลเป็นอะไร?)
print("\n--- ข้อมูลภาพรวม ---")
df.info()

# 5. สถิติเบื้องต้น (ดูค่า Min/Max ของอุณหภูมิว่าถึง 95°C จริงไหม)
print("\n--- สถิติพื้นฐาน ---")
display(df.describe())

--- 5 แถวแรกของข้อมูล ---

,NaCl_Percent,model,Rep,1,2,3,4,5,6,7,...,26,27,28,29,30,31,32,33,34,35
0,0.0,RAW_Temp,RAW_Temp,23.5,23.7,24.0,24.4,24.8,30.0,30.1,...,73.3,73.3,73.6,73.7,73.6,82.0,82.1,82.3,82.4,82.4
1,0.0,model01,M_Temp,2362.0,2360.0,2422.0,2463.0,2478.0,2746.0,2896.0,...,6026.0,6653.0,6864.0,6928.0,6914.0,6914.0,7475.0,7664.0,7692.0,7768.0
2,0.0,model01,EC,62.0,48.0,50.0,48.0,48.0,50.0,50.0,...,65.0,65.0,65.0,64.0,64.0,69.0,68.0,68.0,68.0,67.0
3,0.0,RAW_Temp,RAW_Temp,25.3,25.3,25.3,25.3,25.3,32.1,32.0,...,73.9,74.0,74.0,74.3,74.3,82.9,83.3,83.1,83.4,83.6
4,0.0,model02,M_Temp,2558.0,2550.0,2553.0,2546.0,2548.0,3043.0,3130.0,...,5984.0,6808.0,6987.0,7054.0,7046.0,6822.0,7654.0,7896.0,7947.0,8160.0

--- ข้อมูลภาพรวม ---
<class 'pandas.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 38 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   NaCl_Percent  252 non-null    float64
 1   model         252 non-null    str
 2   Rep           252 non-null    str
 3   1             252 non-null    float64
 4   2             252 non-null    float64
 5   3             252 non-null    float64
 6   4             252 non-null    float64
 7   5             252 non-null    float64
 8   6             252 non-null    float64
 9   7             252 non-null    float64
 10  8             252 non-null    float64
 11  9             252 non-null    float64
 12  10            252 non-null    float64
 13  11            252 non-null    float64
 14  12            252 non-null    float64
 15  13            252 non-null    float64
 16  14            252 non-null    float64
 17  15            252 non-null    float64
 18  16            252 non-null    float64
 19  17            252 non-null    float64
 20  18            252 non-null    float64
 21  19            252 non-null    float64
 22  20            252 non-null    float64
 23  21            252 non-null    float64
 24  22            252 non-null    float64
 25  23            252 non-null    float64
 26  24            252 non-null    float64
 27  25            251 non-null    float64
 28  26            252 non-null    float64
 29  27            252 non-null    float64
 30  28            252 non-null    float64
 31  29            252 non-null    float64
 32  30            252 non-null    float64
 33  31            252 non-null    float64
 34  32            252 non-null    float64
 35  33            252 non-null    float64
 36  34            252 non-null    float64
 37  35            252 non-null    float64
dtypes: float64(36), str(2)
memory usage: 74.9 KB

--- สถิติพื้นฐาน ---

,NaCl_Percent,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
count,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,...,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000
mean,1.000000,937.724603,938.097222,938.742460,939.660714,941.277381,1119.980556,1160.415476,1172.028175,1177.456349,...,2135.382540,2376.075794,2419.885317,2455.280556,2468.379762,2365.725794,2637.652381,2708.536905,2736.050397,2747.755952
std,0.606735,1074.712010,1074.837796,1075.669326,1076.459310,1078.662807,1301.943195,1357.920722,1373.752159,1381.275384,...,2576.074277,2909.735921,2975.954132,3018.002129,3035.040266,2871.359664,3248.324187,3345.189324,3379.211381,3396.993214
min,0.000000,22.600000,22.600000,22.600000,22.600000,22.600000,29.600000,29.600000,29.600000,29.600000,...,64.000000,63.000000,64.000000,63.000000,64.000000,66.000000,67.000000,65.000000,65.000000,65.000000
25%,0.500000,25.500000,25.500000,25.500000,25.500000,25.500000,32.950000,33.225000,33.300000,33.500000,...,74.600000,74.850000,74.825000,75.000000,74.975000,86.600000,86.675000,86.575000,86.600000,86.450000
50%,1.000000,376.500000,376.000000,376.000000,376.500000,377.500000,400.500000,405.500000,406.000000,406.000000,...,657.000000,658.500000,646.000000,657.500000,657.000000,718.500000,722.500000,731.500000,723.500000,713.500000
75%,1.500000,2338.500000,2345.000000,2322.000000,2345.000000,2345.750000,2847.250000,2982.250000,3022.750000,3040.750000,...,5429.500000,6256.750000,6402.500000,6422.500000,6519.500000,5881.750000,6719.750000,7003.000000,7122.000000,7130.250000
max,2.000000,2702.000000,2695.000000,2692.000000,2685.000000,2695.000000,3190.000000,3297.000000,3364.000000,3343.000000,...,7177.000000,7739.000000,7608.000000,7536.000000,7645.000000,8052.000000,8762.000000,8681.000000,8551.000000,8762.000000